x-postgres-environment: &x-postgres-environment
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_HOST: ${POSTGRES_HOST}
  POSTGRES_PORT: ${POSTGRES_PORT}
  POSTGRES_NAME: ${POSTGRES_NAME}

x-rabbit-environment: &x-rabbit-environment
  RABBITMQ_DEFAULT_HOST: ${RABBIT_HOST}
  RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
  RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD}

x-minio-environment: &x-minio-environment
  MINIO_ROOT_HOST: ${MINIO_HOST}
  MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
  MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}

x-oauth-environment: &x-oauth-environment
  YANDEX_OAUTH_ENDPOINT: ${YANDEX_OAUTH_ENDPOINT}
  VK_OAUTH_ENDPOINT: ${VK_OAUTH_ENDPOINT}

include:
  - docker-compose.core-services.yaml

services:
  vixenhealth_id:
    build:
      context: containers/vixenhealth_id
      target: debug

    environment:
      <<: [ *x-rabbit-environment, *x-postgres-environment, *x-minio-environment, *x-oauth-environment ]
      PROJECT_VERSION: ${PROJECT_VERSION}
      PROJECT_SECRET_KEY: ${PROJECT_SECRET_KEY}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}

    command: uvicorn main:app --host=0.0.0.0 --port=8000
    volumes:
      - "./containers/vixenhealth_id/app:/application"
