"""empty message

Revision ID: 0ae56ab3fe9d
Revises: cc2d0af31c33
Create Date: 2024-05-19 18:50:57.408491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ae56ab3fe9d'
down_revision: Union[str, None] = 'cc2d0af31c33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('need_change_password', sa.Boolean(), default=False, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'need_change_password')
    # ### end Alembic commands ###
