"""empty message

Revision ID: 9b8acdbdb89d
Revises: 08204492bdb6
Create Date: 2024-05-13 14:31:06.283183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from storages.database.types.bytestring import ByteString

# revision identifiers, used by Alembic.
revision: str = '9b8acdbdb89d'
down_revision: Union[str, None] = '08204492bdb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('access_mask', ByteString(), nullable=False))
    op.create_unique_constraint(None, 'account', ['id'])
    op.create_unique_constraint(None, 'passport', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'passport', type_='unique')
    op.drop_constraint(None, 'account', type_='unique')
    op.drop_column('account', 'access_mask')
    # ### end Alembic commands ###
