"""empty message

Revision ID: cc2d0af31c33
Revises: d5c570b6c654
Create Date: 2024-05-16 21:09:04.931635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc2d0af31c33'
down_revision: Union[str, None] = 'd5c570b6c654'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('account_username_email_password', 'account', ['username', 'email', 'password'], unique=True)
    op.create_index('application_description_name', 'application', ['description', 'name'], unique=True)
    op.create_index('application_name', 'application', ['name'], unique=True)
    op.create_index('permission_name_codename', 'permission', ['name', 'codename'], unique=True)
    op.create_index('role_name', 'role', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('role_name', table_name='role')
    op.drop_index('permission_name_codename', table_name='permission')
    op.drop_index('application_name', table_name='application')
    op.drop_index('application_description_name', table_name='application')
    op.drop_index('account_username_email_password', table_name='account')
    # ### end Alembic commands ###
