"""empty message

Revision ID: d5c570b6c654
Revises: 2d170b93d249
Create Date: 2024-05-14 17:19:46.088835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5c570b6c654'
down_revision: Union[str, None] = '2d170b93d249'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'application', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'application', type_='unique')
    # ### end Alembic commands ###
