global:
  scrape_interval: 15s # интервал очистки
  scrape_timeout: 10s # сколько ждать очистки
  evaluation_interval: 15s # как часто оценивать правила

alerting:
  alertmanagers:
    - follow_redirects: true
      enable_http2: true
      scheme: http
      timeout: 15s
      api_version: v2
      static_configs:
        - targets: [ ]

scrape_configs:
  - job_name: 'prometheus'
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    static_configs:
      - targets:
          - prometheus:9090

  - job_name: 'vixen_id'
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets:
        - 'vixenhealth_id:8000'