{
 "title": "Vixen ID dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Total requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "variance" ] } },
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_count{job=\"vixen_id\", handler!=\"/metrics\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Среднее время запроса",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_request_duration_highr_seconds_bucket{le!=\"60.0\", le!=\"30.0\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "\"200\" Responses by paths",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "increase(http_requests_total{job=\"vixen_id\", handler!=\"/metrics\", status=\"2xx\"}[1m])",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "\"400\" Responses by paths",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "increase(http_requests_total{job=\"vixen_id\", handler!=\"/metrics\", status=\"4xx\"}[1m])",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "\"500\" Responses by paths",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "increase(http_requests_total{job=\"vixen_id\", handler!=\"/metrics\", status=\"5xx\"}[1m])",
     "legendFormat": "{{handler}}"
    }
   ]
  }
 ]
}